'use client';

import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { useLocale } from 'next-intl';
import { routing, Locale, createLocalizedPath } from '@/i18n/routing';

type Language = Locale;

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    dir: 'ltr' | 'rtl';
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
    en: {
        'nav.browse': 'Browse Venues',
        'nav.how': 'How It Works',
        'nav.owners': 'For Owners',
        'nav.signin': 'Sign In',
        'nav.list_venue': 'List Your Venue',
        'hero.title': 'Find the Perfect Venue for Your Event',
        'hero.subtitle': 'The #1 marketplace for wedding halls, salons, and event venues in Algeria.',
        'search.placeholder': 'Search venues...',
        'search.location': 'All Locations',
        'search.btn': 'Search',
        'settings.title': 'Settings',
        'settings.desc': 'Manage your account and profile',
        'settings.profile': 'Profile',
        'settings.save': 'Save Changes',
        'settings.saving': 'Saving...',
        'settings.upload': 'Change Photo',
        'settings.uploading': 'Uploading...',
        'settings.email': 'Email',
        'settings.fullname': 'Personal Name',
        'settings.phone': 'Phone',
        'settings.businessname': 'Business Name',
        'settings.businessdesc': 'Business Description',
        'settings.businessplaceholder': 'e.g. Wedding Hall Algiers',
        'settings.setup_title': 'Complete your profile',
        'settings.setup_desc': 'Fill in your information here. Your plan, receipt, and review status are all managed in settings.',
        'settings.setup_hint': 'Keep this page updated so the admin team can review and activate your account faster.',
        'settings.complete': 'Completed',
        'settings.missing': 'Missing',
        'settings.personal_section': 'Personal information',
        'settings.business_section': 'Venue owner profile',
        'settings.billing.title': 'Plan and payment',
        'settings.billing.desc': 'Choose your pack, upload your receipt, and track your review status here.',
        'settings.billing.title_short': 'Plan',
        'settings.billing.current_title': 'Current request',
        'settings.billing.current_pack': 'Pack',
        'settings.billing.current_status': 'Status',
        'settings.billing.current_starts': 'Starts',
        'settings.billing.current_ends': 'Ends',
        'settings.billing.no_subscription': 'No subscription has been requested yet.',
        'settings.billing.choose_plan': 'Choose a pack',
        'settings.billing.choose_plan_desc': 'Select the plan that matches your venue needs.',
        'settings.billing.no_plans': 'No plans are available right now.',
        'settings.billing.owner_pack': 'Owner Pack',
        'settings.billing.selected': 'Selected',
        'settings.billing.per_month': 'per month',
        'settings.billing.duration': '{months} months',
        'settings.billing.for_duration': 'for {months} months',
        'settings.billing.baridimob': 'Baridimob',
        'settings.billing.ask_admin_baridimob': 'Ask admin to configure Baridimob info.',
        'settings.billing.baridimob_receipt': 'Baridimob receipt',
        'settings.billing.contact_admin': 'Contact admin',
        'settings.billing.max_images': 'Images per venue',
        'settings.billing.max_videos': 'Videos per venue',
        'settings.billing.manual_payment': 'Manual payment',
        'settings.billing.manual_payment_desc': 'Use the payment details below, then upload your receipt.',
        'settings.billing.ccp': 'CCP',
        'settings.billing.bank': 'Bank',
        'settings.billing.ask_admin_ccp': 'Ask admin to configure the CCP number.',
        'settings.billing.ask_admin_bank': 'Ask admin to configure the bank account.',
        'settings.billing.payment_method': 'Payment method',
        'settings.billing.ccp_receipt': 'CCP receipt',
        'settings.billing.bank_receipt': 'Bank transfer receipt',
        'settings.billing.upload_receipt': 'Upload receipt',
        'settings.billing.uploading_receipt': 'Uploading...',
        'settings.billing.choose_receipt': 'Choose receipt image or PDF',
        'settings.billing.online_payment': 'Online payment',
        'settings.billing.online_payment_desc': 'Use the direct payment link if it is configured.',
        'settings.billing.continue_online_payment': 'Continue to online payment',
        'settings.billing.online_payment_missing': 'No online payment link is configured yet. You can still upload a manual receipt.',
        'settings.billing.selected_plan': 'Selected pack',
        'settings.billing.select_plan_first': 'Choose a pack first',
        'settings.billing.month_short': 'month',
        'settings.billing.receipt_history': 'Receipt history',
        'settings.billing.no_receipts': 'No receipts submitted yet.',
        'settings.billing.receipt_label': 'Payment receipt',
        'settings.billing.view_receipt': 'View receipt',
        'settings.billing.admin_note': 'Admin note',
        'settings.billing.receipt_success': 'Receipt uploaded successfully. Your request is now waiting for admin review.',
        'settings.billing.receipt_error': 'Could not upload your receipt.',
        'settings.billing.status_active': 'Active',
        'settings.billing.status_pending': 'Pending',
        'settings.billing.status_expired': 'Expired',
        'settings.billing.status_cancelled': 'Cancelled',
        'settings.pending.badge': 'Account review in progress',
        'settings.pending.title': 'Finish your setup while we review your account',
        'settings.pending.desc': 'Complete your business profile, choose your pack, and upload your payment receipt. Once approved, you can publish venues and start receiving inquiries.',
        'settings.pending.venue_workspace': 'Venue workspace',
        'settings.pending.step': 'Step',
        'settings.pending.step1': 'Complete owner profile',
        'settings.pending.step2': 'Pick a subscription pack',
        'settings.pending.step3': 'Upload receipt & wait for approval',
        'settings.pending.fields_done': 'fields completed',
        'settings.pending.no_pack': 'No pack selected yet',
        'settings.pending.receipt_submitted': 'receipt submitted',
        'settings.pending.no_receipt': 'No receipt uploaded yet',
        'settings.pending.venue_limit_hint': 'Choose a pack to see your venue limit',
        'settings.pending.first_venue': 'Set your first venue page',
        'settings.pending.slots_remaining': 'venue slots remaining',
        'settings.success_avatar': 'Avatar updated successfully',
        'settings.success_profile': 'Profile updated successfully!',
        'dashboard.nav.home': 'Dashboard',
        'dashboard.nav.venues': 'My Venues',
        'dashboard.nav.inquiries': 'Inquiries',
        'dashboard.nav.settings': 'Settings',
        'dashboard.status.active': 'Active',
        'dashboard.status.pending': 'Pending Approval',
        'dashboard.status.pending_desc': 'Your account is under review.',
        'dashboard.status.review_time': 'This usually takes 24-48 hours.',
        'dashboard.status.rejected': 'Account Rejected',
        'dashboard.status.rejected_desc': 'Please contact support.',
        'dashboard.header.signout': 'Sign out',
        'dashboard.btn.add_venue': 'Add New Venue',
        'dashboard.welcome.title': 'Welcome back',
        'dashboard.welcome.subtitle': 'Manage your venues and track your performance.',
        'dashboard.stats.total_venues': 'Total Venues',
        'dashboard.stats.pending': 'Pending Review',
        'dashboard.stats.inquiries': 'Inquiries',
        'dashboard.stats.views': 'Total Views',
        'dashboard.actions.add_title': 'Add New Venue',
        'dashboard.actions.add_desc': 'List your venue and reach customers',
        'dashboard.actions.venues_title': 'My Venues',
        'dashboard.actions.venues_desc': 'View and manage your listings',
        'dashboard.actions.inquiries_title': 'Inquiries',
        'dashboard.actions.inquiries_desc': 'Check customer messages',
        'dashboard.actions.settings_title': 'Settings',
        'dashboard.actions.settings_desc': 'Update your profile',
        'venues.title': 'My Venues',
        'venues.subtitle': 'Manage your venue listings',
        'venues.empty': 'No Venues Found',
        'venues.empty_all': "You haven't added any venues yet.",
        'venues.btn.view': 'View',
        'venues.btn.edit': 'Edit',
        'venues.pages_label': 'Venue pages',
        'venues.pages_title': 'Build a profile page for every venue',
        'venues.pages_desc': 'Each venue can have its own public page with photos, amenities, contact details, and pricing. Use the edit button on any venue card to keep each page fresh.',
        'venues.plan_capacity': 'Plan capacity',
        'venues.choose_pack': 'Choose a billing pack to unlock venue limits.',
        'venues.can_add_more': 'You can still add more venue pages on this pack.',
        'venues.limit_reached': 'You have reached your current venue limit. Upgrade or replace an existing listing.',
        'venues.untitled': 'Untitled',
        'venues.no_location': 'No location',
        'venues.uncategorized': 'Uncategorized',
        'venues.under_review': 'Under review. This usually takes 24-48 hours.',
        'inquiries.title': 'Inquiries',
        'inquiries.subtitle': 'Manage customer inquiries for your venues',
        'inquiries.empty': 'No Inquiries',
        'inquiries.empty_all': "You haven't received any inquiries yet.",
        'inquiries.select': 'Select an Inquiry',
        'inquiries.select_desc': 'Click on an inquiry to view details',
        'inquiries.details.date': 'Event Date',
        'inquiries.details.guests': 'Guests',
        'inquiries.details.type': 'Event Type',
        'inquiries.details.phone': 'Phone',
        'inquiries.details.message': 'Message',
        'inquiries.btn.whatsapp': 'WhatsApp',
        'inquiries.btn.call': 'Call',
        'inquiries.btn.replied': 'Mark as Replied',
        'inquiries.btn.close': 'Close',
        'status.all': 'All',
        'status.approved': 'Approved',
        'status.pending': 'Pending',
        'status.rejected': 'Rejected',
        'status.draft': 'Draft',
        'status.published': 'Published',
        'status.new': 'New',
        'status.read': 'Read',
        'status.replied': 'Replied',
        'status.closed': 'Closed',
        'admin.title': 'Admin Panel',
        'admin.nav.dashboard': 'Dashboard',
        'admin.nav.venues': 'Venues',
        'admin.nav.users': 'Users',
        'admin.nav.inquiries': 'Inquiries',
        'admin.nav.settings': 'Settings',
        'admin.dashboard.title': 'Admin Dashboard',
        'admin.dashboard.subtitle': 'Monitor and manage your platform',
        'admin.status.pending': 'Pending',
        'admin.status.approved': 'Approved',
        'admin.status.rejected': 'Rejected',
        'admin.status.published': 'Published',
        'admin.status.active': 'Active',
        'admin.stats.pending_venues': 'Pending Venues',
        'admin.stats.active_venues': 'Active Venues',
        'admin.stats.pending_users': 'Pending Users',
        'admin.stats.active_users': 'Active Users',
        'admin.stats.review_now': 'Review now',
        'admin.stats.view_all': 'View all',
        'admin.stats.review': 'Review',
        'admin.stats.total': 'Total',
        'admin.actions.title': 'Quick Actions',
        'admin.actions.manage_venues': 'Manage Venues',
        'admin.actions.manage_venues_desc': 'Review and approve venues',
        'admin.actions.manage_users': 'Manage Users',
        'admin.actions.manage_users_desc': 'Review venue owners',
        'admin.actions.view_inquiries': 'View Inquiries',
        'admin.actions.view_inquiries_desc': 'Monitor customer requests',
        'admin.activity.title': 'Recent Activity',
        'admin.activity.empty': 'No recent activity',
        'admin.activity.empty_desc': 'Activity logs will appear here',
        'dashboard.nav.notifications': 'Notifications',
        'dashboard.nav.approval_required': 'Account approval required',
        'settings.desc_placeholder': 'Tell us about your venue business...',
        'settings.billing.subscription_expired': 'Your subscription has expired',
        'settings.billing.subscription_expired_desc': 'Renew your pack to reactivate your venue.',
        'settings.billing.subscription_expiring': 'Your subscription expires in {days} days',
        'settings.billing.limited_offer': 'Limited offer',
        'settings.billing.venue_count': 'venue',
    },
    fr: {
        'nav.browse': 'Parcourir les lieux',
        'nav.how': 'Comment ça marche',
        'nav.owners': 'Pour les propriétaires',
        'nav.signin': 'Se connecter',
        'nav.list_venue': 'Ajouter votre lieu',
        'hero.title': 'Trouvez le lieu idéal pour votre événement',
        'hero.subtitle': 'La première place de marché pour les salles des fêtes et les lieux événementiels en Algérie.',
        'search.placeholder': 'Rechercher des lieux...',
        'search.location': 'Toutes les villes',
        'search.btn': 'Rechercher',
        'settings.title': 'Paramètres',
        'settings.desc': 'Gérer votre compte et votre profil',
        'settings.profile': 'Profil',
        'settings.save': 'Enregistrer',
        'settings.saving': 'Enregistrement...',
        'settings.upload': 'Changer la photo',
        'settings.uploading': 'Téléchargement...',
        'settings.email': 'Email',
        'settings.fullname': 'Nom complet',
        'settings.phone': 'Téléphone',
        'settings.businessname': 'Nom de l\'entreprise (Business)',
        'settings.businessdesc': 'Description de l\'entreprise',
        'settings.businessplaceholder': 'ex. Salle des Fêtes Alger',
        'settings.setup_title': 'Complétez votre profil',
        'settings.setup_desc': 'Renseignez vos informations ici. Votre formule, votre reçu et le statut de revue sont tous gérés dans les paramètres.',
        'settings.setup_hint': 'Gardez cette page à jour pour aider l\'équipe admin à revoir et activer votre compte plus rapidement.',
        'settings.complete': 'Complété',
        'settings.missing': 'Manquant',
        'settings.personal_section': 'Informations personnelles',
        'settings.business_section': 'Profil propriétaire',
        'settings.billing.title': 'Formule et paiement',
        'settings.billing.desc': 'Choisissez votre pack, téléversez votre reçu et suivez le statut ici.',
        'settings.billing.title_short': 'Formule',
        'settings.billing.current_title': 'Demande actuelle',
        'settings.billing.current_pack': 'Pack',
        'settings.billing.current_status': 'Statut',
        'settings.billing.current_starts': 'Début',
        'settings.billing.current_ends': 'Fin',
        'settings.billing.no_subscription': 'Aucun abonnement n\'a encore été demandé.',
        'settings.billing.choose_plan': 'Choisir un pack',
        'settings.billing.choose_plan_desc': 'Sélectionnez la formule adaptée à votre salle.',
        'settings.billing.no_plans': 'Aucun pack n\'est disponible pour le moment.',
        'settings.billing.owner_pack': 'Pack propriétaire',
        'settings.billing.selected': 'Sélectionné',
        'settings.billing.per_month': 'par mois',
        'settings.billing.duration': '{months} mois',
        'settings.billing.for_duration': 'pour {months} mois',
        'settings.billing.baridimob': 'Baridimob',
        'settings.billing.ask_admin_baridimob': 'Demandez à l\'admin de configurer Baridimob.',
        'settings.billing.baridimob_receipt': 'Reçu Baridimob',
        'settings.billing.contact_admin': 'Contacter l\'admin',
        'settings.billing.max_images': 'Images par salle',
        'settings.billing.max_videos': 'Vidéos par salle',
        'settings.billing.manual_payment': 'Paiement manuel',
        'settings.billing.manual_payment_desc': 'Utilisez les informations ci-dessous, puis téléversez votre reçu.',
        'settings.billing.ccp': 'CCP',
        'settings.billing.bank': 'Banque',
        'settings.billing.ask_admin_ccp': 'Demandez à l\'admin de configurer le numéro CCP.',
        'settings.billing.ask_admin_bank': 'Demandez à l\'admin de configurer le compte bancaire.',
        'settings.billing.payment_method': 'Mode de paiement',
        'settings.billing.ccp_receipt': 'Reçu CCP',
        'settings.billing.bank_receipt': 'Reçu virement bancaire',
        'settings.billing.upload_receipt': 'Téléverser le reçu',
        'settings.billing.uploading_receipt': 'Téléversement...',
        'settings.billing.choose_receipt': 'Choisir une image ou un PDF',
        'settings.billing.online_payment': 'Paiement en ligne',
        'settings.billing.online_payment_desc': 'Utilisez le lien direct si la passerelle est configurée.',
        'settings.billing.continue_online_payment': 'Continuer vers le paiement',
        'settings.billing.online_payment_missing': 'Aucun lien de paiement en ligne n\'est configuré pour le moment. Vous pouvez toujours téléverser un reçu manuel.',
        'settings.billing.selected_plan': 'Pack sélectionné',
        'settings.billing.select_plan_first': 'Choisissez d\'abord un pack',
        'settings.billing.month_short': 'mois',
        'settings.billing.receipt_history': 'Historique des reçus',
        'settings.billing.no_receipts': 'Aucun reçu envoyé pour le moment.',
        'settings.billing.receipt_label': 'Reçu de paiement',
        'settings.billing.view_receipt': 'Voir le reçu',
        'settings.billing.admin_note': 'Note admin',
        'settings.billing.receipt_success': 'Le reçu a bien été téléversé. Votre demande attend maintenant la revue de l\'admin.',
        'settings.billing.receipt_error': 'Impossible de téléverser votre reçu.',
        'settings.billing.status_active': 'Actif',
        'settings.billing.status_pending': 'En attente',
        'settings.billing.status_expired': 'Expiré',
        'settings.billing.status_cancelled': 'Annulé',
        'settings.pending.badge': 'Vérification du compte en cours',
        'settings.pending.title': 'Terminez votre configuration pendant que nous vérifions votre compte',
        'settings.pending.desc': 'Complétez votre profil, choisissez votre pack et téléchargez votre reçu de paiement. Une fois approuvé, vous pourrez publier vos salles et recevoir des demandes.',
        'settings.pending.venue_workspace': 'Espace salle',
        'settings.pending.step': 'Étape',
        'settings.pending.step1': 'Compléter le profil propriétaire',
        'settings.pending.step2': 'Choisir un pack d\'abonnement',
        'settings.pending.step3': 'Télécharger le reçu et attendre l\'approbation',
        'settings.pending.fields_done': 'champs complétés',
        'settings.pending.no_pack': 'Aucun pack sélectionné',
        'settings.pending.receipt_submitted': 'reçu soumis',
        'settings.pending.no_receipt': 'Aucun reçu téléchargé',
        'settings.pending.venue_limit_hint': 'Choisissez un pack pour voir votre limite de salles',
        'settings.pending.first_venue': 'Créez votre première page de salle',
        'settings.pending.slots_remaining': 'emplacements de salle restants',
        'settings.success_avatar': 'Avatar mis à jour avec succès',
        'settings.success_profile': 'Profil mis à jour avec succès !',
        'dashboard.nav.home': 'Tableau de bord',
        'dashboard.nav.venues': 'Mes Lieux',
        'dashboard.nav.inquiries': 'Demandes',
        'dashboard.nav.settings': 'Paramètres',
        'dashboard.status.active': 'Actif',
        'dashboard.status.pending': 'En attente d\'approbation',
        'dashboard.status.pending_desc': 'Votre compte est en cours d\'examen.',
        'dashboard.status.review_time': 'Cela prend généralement 24 à 48 heures.',
        'dashboard.status.rejected': 'Compte rejeté',
        'dashboard.status.rejected_desc': 'Veuillez contacter le support.',
        'dashboard.header.signout': 'Se déconnecter',
        'dashboard.btn.add_venue': 'Ajouter un lieu',
        'dashboard.welcome.title': 'Bon retour',
        'dashboard.welcome.subtitle': 'Gérez vos lieux et suivez vos performances.',
        'dashboard.stats.total_venues': 'Total des lieux',
        'dashboard.stats.pending': 'En attente',
        'dashboard.stats.inquiries': 'Demandes',
        'dashboard.stats.views': 'Vues totales',
        'dashboard.actions.add_title': 'Ajouter un lieu',
        'dashboard.actions.add_desc': 'Listez votre lieu et atteignez des clients',
        'dashboard.actions.venues_title': 'Mes Lieux',
        'dashboard.actions.venues_desc': 'Voir et gérer vos annonces',
        'dashboard.actions.inquiries_title': 'Demandes',
        'dashboard.actions.inquiries_desc': 'Vérifier les messages des clients',
        'dashboard.actions.settings_title': 'Paramètres',
        'dashboard.actions.settings_desc': 'Mettre à jour votre profil',
        'venues.title': 'Mes Lieux',
        'venues.subtitle': 'Gérer vos annonces de lieux',
        'venues.empty': 'Aucun lieu trouvé',
        'venues.empty_all': "Vous n'avez pas encore ajouté de lieux.",
        'venues.btn.view': 'Voir',
        'venues.btn.edit': 'Modifier',
        'venues.pages_label': 'Pages de salle',
        'venues.pages_title': 'Créez une page profil pour chaque salle',
        'venues.pages_desc': 'Chaque salle peut avoir sa propre page publique avec photos, équipements, coordonnées et tarifs. Utilisez le bouton modifier pour garder chaque page à jour.',
        'venues.plan_capacity': 'Capacité du plan',
        'venues.choose_pack': 'Choisissez un pack pour débloquer les limites de salles.',
        'venues.can_add_more': 'Vous pouvez encore ajouter des pages de salle avec ce pack.',
        'venues.limit_reached': 'Vous avez atteint votre limite. Passez à un pack supérieur ou remplacez une annonce.',
        'venues.untitled': 'Sans titre',
        'venues.no_location': 'Pas de lieu',
        'venues.uncategorized': 'Non catégorisé',
        'venues.under_review': 'En cours de vérification. Cela prend généralement 24 à 48 heures.',
        'inquiries.title': 'Demandes',
        'inquiries.subtitle': 'Gérer les demandes clients pour vos lieux',
        'inquiries.empty': 'Aucune demande',
        'inquiries.empty_all': "Vous n'avez reçu aucune demande pour le moment.",
        'inquiries.select': 'Sélectionnez une demande',
        'inquiries.select_desc': 'Cliquez sur une demande pour voir les détails',
        'inquiries.details.date': 'Date événement',
        'inquiries.details.guests': 'Invités',
        'inquiries.details.type': 'Type événement',
        'inquiries.details.phone': 'Téléphone',
        'inquiries.details.message': 'Message',
        'inquiries.btn.whatsapp': 'WhatsApp',
        'inquiries.btn.call': 'Appeler',
        'inquiries.btn.replied': 'Marquer comme répondu',
        'inquiries.btn.close': 'Fermer',
        'status.all': 'Tout',
        'status.approved': 'Approuvé',
        'status.pending': 'En attente',
        'status.rejected': 'Rejeté',
        'status.draft': 'Brouillon',
        'status.published': 'Publié',
        'status.new': 'Nouveau',
        'status.read': 'Lu',
        'status.replied': 'Répondu',
        'status.closed': 'Fermé',
        'admin.title': 'Panneau d\'Administration',
        'admin.nav.dashboard': 'Tableau de Bord',
        'admin.nav.venues': 'Salles',
        'admin.nav.users': 'Utilisateurs',
        'admin.nav.inquiries': 'Demandes',
        'admin.nav.settings': 'Paramètres',
        'admin.dashboard.title': 'Tableau de Bord Admin',
        'admin.dashboard.subtitle': 'Surveillez et gérez votre plateforme',
        'admin.status.pending': 'En Attente',
        'admin.status.approved': 'Approuvé',
        'admin.status.rejected': 'Rejeté',
        'admin.status.published': 'Publié',
        'admin.status.active': 'Actif',
        'admin.stats.pending_venues': 'Salles en Attente',
        'admin.stats.active_venues': 'Salles Actives',
        'admin.stats.pending_users': 'Utilisateurs en Attente',
        'admin.stats.active_users': 'Utilisateurs Actifs',
        'admin.stats.review_now': 'Vérifier',
        'admin.stats.view_all': 'Voir tout',
        'admin.stats.review': 'Révision',
        'admin.stats.total': 'Total',
        'admin.actions.title': 'Actions Rapides',
        'admin.actions.manage_venues': 'Gérer les Salles',
        'admin.actions.manage_venues_desc': 'Examiner et approuver les salles',
        'admin.actions.manage_users': 'Gérer les Utilisateurs',
        'admin.actions.manage_users_desc': 'Vérifier les propriétaires de salles',
        'admin.actions.view_inquiries': 'Voir les Demandes',
        'admin.actions.view_inquiries_desc': 'Suivre les demandes clients',
        'admin.activity.title': 'Activité Récente',
        'admin.activity.empty': 'Aucune activité récente',
        'admin.activity.empty_desc': 'Les journaux d\'activité apparaîtront ici',
        'dashboard.nav.notifications': 'Notifications',
        'dashboard.nav.approval_required': 'Approbation du compte requise',
        'settings.desc_placeholder': 'Décrivez votre activité de salle...',
        'settings.billing.subscription_expired': 'Votre abonnement a expiré',
        'settings.billing.subscription_expired_desc': 'Renouvelez votre pack pour réactiver votre salle.',
        'settings.billing.subscription_expiring': 'Votre abonnement expire dans {days} jours',
        'settings.billing.limited_offer': 'Offre limitée',
        'settings.billing.venue_count': 'salle',
    },
    ar: {
        'nav.browse': 'تصفح القاعات',
        'nav.how': 'كيف يعمل',
        'nav.owners': 'لأصحاب القاعات',
        'nav.signin': 'تسجيل الدخول',
        'nav.list_venue': 'أضف قاعتك',
        'hero.title': 'اعثر على المكان المثالي لمناسبتك',
        'hero.subtitle': 'أكبر سوق لقاعات الأفراح والمناسبات في الجزائر.',
        'search.placeholder': 'ابحث عن قاعات...',
        'search.location': 'كل الولايات',
        'search.btn': 'بحث',
        'settings.title': 'الإعدادات',
        'settings.desc': 'إدارة حسابك وملفك الشخصي',
        'settings.profile': 'الملف الشخصي',
        'settings.save': 'حفظ التغييرات',
        'settings.saving': 'جاري الحفظ...',
        'settings.upload': 'تغيير الصورة',
        'settings.uploading': 'جاري التحميل...',
        'settings.email': 'البريد الإلكتروني',
        'settings.fullname': 'الاسم الكامل',
        'settings.phone': 'الهاتف',
        'settings.businessname': 'اسم العمل التجاري',
        'settings.businessdesc': 'وصف العمل',
        'settings.businessplaceholder': 'مثال: قاعة أفراح الجزائر',
        'settings.setup_title': 'أكمل ملفك',
        'settings.setup_desc': 'أدخل معلوماتك من هنا. الباقة والإيصال وحالة المراجعة كلها في صفحة الإعدادات.',
        'settings.setup_hint': 'حدّث هذه الصفحة دائما ليساعد ذلك فريق الإدارة على مراجعة حسابك وتفعيله بسرعة أكبر.',
        'settings.complete': 'مكتمل',
        'settings.missing': 'ناقص',
        'settings.personal_section': 'المعلومات الشخصية',
        'settings.business_section': 'ملف مالك القاعة',
        'settings.billing.title': 'الباقة والدفع',
        'settings.billing.desc': 'اختر باقتك وارفع الإيصال وتابع حالة المراجعة من هنا.',
        'settings.billing.title_short': 'الباقة',
        'settings.billing.current_title': 'الطلب الحالي',
        'settings.billing.current_pack': 'الباقة',
        'settings.billing.current_status': 'الحالة',
        'settings.billing.current_starts': 'يبدأ',
        'settings.billing.current_ends': 'ينتهي',
        'settings.billing.no_subscription': 'لم يتم طلب أي اشتراك بعد.',
        'settings.billing.choose_plan': 'اختر باقة',
        'settings.billing.choose_plan_desc': 'اختر الباقة المناسبة لاحتياجات قاعتك.',
        'settings.billing.no_plans': 'لا توجد باقات متاحة حاليا.',
        'settings.billing.owner_pack': 'باقة المالك',
        'settings.billing.selected': 'محددة',
        'settings.billing.per_month': 'كل شهر',
        'settings.billing.duration': '{months} أشهر',
        'settings.billing.for_duration': 'لمدة {months} أشهر',
        'settings.billing.baridimob': 'بريدي موب',
        'settings.billing.ask_admin_baridimob': 'اطلب من الإدارة إضافة معلومات بريدي موب.',
        'settings.billing.baridimob_receipt': 'إيصال بريدي موب',
        'settings.billing.contact_admin': 'تواصل مع الإدارة',
        'settings.billing.max_images': 'الصور لكل قاعة',
        'settings.billing.max_videos': 'الفيديوهات لكل قاعة',
        'settings.billing.manual_payment': 'الدفع اليدوي',
        'settings.billing.manual_payment_desc': 'استخدم معلومات الدفع أدناه ثم ارفع الإيصال.',
        'settings.billing.ccp': 'CCP',
        'settings.billing.bank': 'البنك',
        'settings.billing.ask_admin_ccp': 'اطلب من الإدارة إضافة رقم CCP.',
        'settings.billing.ask_admin_bank': 'اطلب من الإدارة إضافة معلومات الحساب البنكي.',
        'settings.billing.payment_method': 'طريقة الدفع',
        'settings.billing.ccp_receipt': 'إيصال CCP',
        'settings.billing.bank_receipt': 'إيصال حوالة بنكية',
        'settings.billing.upload_receipt': 'ارفع الإيصال',
        'settings.billing.uploading_receipt': 'جاري الرفع...',
        'settings.billing.choose_receipt': 'اختر صورة أو PDF',
        'settings.billing.online_payment': 'الدفع الإلكتروني',
        'settings.billing.online_payment_desc': 'استخدم رابط الدفع المباشر إذا كان متاحا.',
        'settings.billing.continue_online_payment': 'الانتقال إلى الدفع',
        'settings.billing.online_payment_missing': 'لا يوجد رابط دفع إلكتروني مفعل حاليا. ما زال يمكنك رفع الإيصال اليدوي.',
        'settings.billing.selected_plan': 'الباقة المحددة',
        'settings.billing.select_plan_first': 'اختر باقة أولا',
        'settings.billing.month_short': 'شهر',
        'settings.billing.receipt_history': 'سجل الإيصالات',
        'settings.billing.no_receipts': 'لم يتم رفع أي إيصالات بعد.',
        'settings.billing.receipt_label': 'إيصال دفع',
        'settings.billing.view_receipt': 'عرض الإيصال',
        'settings.billing.admin_note': 'ملاحظة الإدارة',
        'settings.billing.receipt_success': 'تم رفع الإيصال بنجاح. طلبك الآن بانتظار مراجعة الإدارة.',
        'settings.billing.receipt_error': 'تعذر رفع الإيصال.',
        'settings.billing.status_active': 'نشط',
        'settings.billing.status_pending': 'قيد الانتظار',
        'settings.billing.status_expired': 'منتهي',
        'settings.billing.status_cancelled': 'ملغى',
        'settings.pending.badge': 'مراجعة الحساب جارية',
        'settings.pending.title': 'أكمل إعداداتك بينما نراجع حسابك',
        'settings.pending.desc': 'أكمل ملفك التجاري، اختر باقتك، وارفع وصل الدفع. بمجرد الموافقة، يمكنك نشر قاعاتك والبدء في استقبال الطلبات.',
        'settings.pending.venue_workspace': 'مساحة القاعات',
        'settings.pending.step': 'الخطوة',
        'settings.pending.step1': 'إكمال ملف المالك',
        'settings.pending.step2': 'اختيار باقة اشتراك',
        'settings.pending.step3': 'رفع الوصل وانتظار الموافقة',
        'settings.pending.fields_done': 'حقول مكتملة',
        'settings.pending.no_pack': 'لم يتم اختيار باقة بعد',
        'settings.pending.receipt_submitted': 'وصل مرفوع',
        'settings.pending.no_receipt': 'لم يتم رفع أي وصل بعد',
        'settings.pending.venue_limit_hint': 'اختر باقة لمعرفة حد القاعات',
        'settings.pending.first_venue': 'أنشئ صفحة قاعتك الأولى',
        'settings.pending.slots_remaining': 'أماكن قاعات متبقية',
        'settings.success_avatar': 'تم تحديث الصورة بنجاح',
        'settings.success_profile': 'تم تحديث الملف الشخصي بنجاح!',
        'dashboard.nav.home': 'لوحة القيادة',
        'dashboard.nav.venues': 'قاعاتي',
        'dashboard.nav.inquiries': 'الاستفسارات',
        'dashboard.nav.settings': 'الإعدادات',
        'dashboard.status.active': 'نشط',
        'dashboard.status.pending': 'بانتظار الموافقة',
        'dashboard.status.pending_desc': 'حسابك قيد المراجعة.',
        'dashboard.status.review_time': 'عادة ما يستغرق هذا 24-48 ساعة.',
        'dashboard.status.rejected': 'تم رفض الحساب',
        'dashboard.status.rejected_desc': 'يرجى الاتصال بالدعم.',
        'dashboard.header.signout': 'تسجيل الخروج',
        'dashboard.btn.add_venue': 'إضافة قاعة جديدة',
        'dashboard.welcome.title': 'مرحباً بعودتك',
        'dashboard.welcome.subtitle': 'أدر قاعاتك وتتبع أدائك.',
        'dashboard.stats.total_venues': 'إجمالي القاعات',
        'dashboard.stats.pending': 'بانتظار المراجعة',
        'dashboard.stats.inquiries': 'الاستفسارات',
        'dashboard.stats.views': 'إجمالي المشاهدات',
        'dashboard.actions.add_title': 'إضافة قاعة جديدة',
        'dashboard.actions.add_desc': 'اعرض قاعتك وتواصل مع العملاء',
        'dashboard.actions.venues_title': 'قاعاتي',
        'dashboard.actions.venues_desc': 'عرض وإدارة إعلاناتك',
        'dashboard.actions.inquiries_title': 'الاستفسارات',
        'dashboard.actions.inquiries_desc': 'تفقد رسائل العملاء',
        'dashboard.actions.settings_title': 'الإعدادات',
        'dashboard.actions.settings_desc': 'تحديث ملفك الشخصي',
        'venues.title': 'قاعاتي',
        'venues.subtitle': 'إدارة إعلانات القاعات الخاصة بك',
        'venues.empty': 'لم يتم العثور على قاعات',
        'venues.empty_all': "لم تقم بإضافة أي قاعات بعد.",
        'venues.btn.view': 'عرض',
        'venues.btn.edit': 'تعديل',
        'venues.pages_label': 'صفحات القاعات',
        'venues.pages_title': 'أنشئ صفحة لكل قاعة',
        'venues.pages_desc': 'كل قاعة يمكن أن تحتوي على صفحة عامة خاصة بها مع صور ومرافق وتفاصيل الاتصال والأسعار. استخدم زر التعديل لتحديث كل صفحة.',
        'venues.plan_capacity': 'سعة الباقة',
        'venues.choose_pack': 'اختر باقة لفتح حدود القاعات.',
        'venues.can_add_more': 'يمكنك إضافة المزيد من صفحات القاعات مع هذه الباقة.',
        'venues.limit_reached': 'لقد بلغت الحد الأقصى. قم بالترقية أو استبدل إعلاناً موجوداً.',
        'venues.untitled': 'بدون عنوان',
        'venues.no_location': 'بدون موقع',
        'venues.uncategorized': 'غير مصنف',
        'venues.under_review': 'قيد المراجعة. عادة ما يستغرق 24-48 ساعة.',
        'inquiries.title': 'الاستفسارات',
        'inquiries.subtitle': 'إدارة استفسارات العملاء لقاعاتك',
        'inquiries.empty': 'لا توجد استفسارات',
        'inquiries.empty_all': "لم تتلق أي استفسارات حتى الآن.",
        'inquiries.select': 'حدد استفساراً',
        'inquiries.select_desc': 'انقر على استفسار لعرض التفاصيل',
        'inquiries.details.date': 'تاريخ المناسبة',
        'inquiries.details.guests': 'الضيوف',
        'inquiries.details.type': 'نوع الفعالية',
        'inquiries.details.phone': 'الهاتف',
        'inquiries.details.message': 'الرسالة',
        'inquiries.btn.whatsapp': 'واتساب',
        'inquiries.btn.call': 'اتصال',
        'inquiries.btn.replied': 'تم الرد',
        'inquiries.btn.close': 'إغلاق',
        'status.all': 'الكل',
        'status.approved': 'مقبول',
        'status.pending': 'قيد الانتظار',
        'status.rejected': 'مرفوض',
        'status.draft': 'مسودة',
        'status.published': 'منشور',
        'status.new': 'جديد',
        'status.read': 'مقروء',
        'status.replied': 'تم الرد',
        'status.closed': 'مغلق',
        'admin.title': 'لوحة الإدارة',
        'admin.nav.dashboard': 'لوحة التحكم',
        'admin.nav.venues': 'القاعات',
        'admin.nav.users': 'المستخدمين',
        'admin.nav.inquiries': 'الطلبات',
        'admin.nav.settings': 'الإعدادات',
        'admin.dashboard.title': 'لوحة تحكم المشرف',
        'admin.dashboard.subtitle': 'راقب وأدر منصتك',
        'admin.status.pending': 'قيد الانتظار',
        'admin.status.approved': 'موافق عليه',
        'admin.status.rejected': 'مرفوض',
        'admin.status.published': 'منشور',
        'admin.status.active': 'نشط',
        'admin.stats.pending_venues': 'قاعات قيد الانتظار',
        'admin.stats.active_venues': 'قاعات نشطة',
        'admin.stats.pending_users': 'مستخدمين قيد الانتظار',
        'admin.stats.active_users': 'مستخدمين نشطين',
        'admin.stats.review_now': 'مراجعة الآن',
        'admin.stats.view_all': 'عرض الكل',
        'admin.stats.review': 'مراجعة',
        'admin.stats.total': 'إجمالي',
        'admin.actions.title': 'إجراءات سريعة',
        'admin.actions.manage_venues': 'إدارة القاعات',
        'admin.actions.manage_venues_desc': 'مراجعة والموافقة على القاعات',
        'admin.actions.manage_users': 'إدارة المستخدمين',
        'admin.actions.manage_users_desc': 'مراجعة أصحاب القاعات',
        'admin.actions.view_inquiries': 'عرض الطلبات',
        'admin.actions.view_inquiries_desc': 'متابعة طلبات العملاء',
        'admin.activity.title': 'النشاط الأخير',
        'admin.activity.empty': 'لا يوجد نشاط حديث',
        'admin.activity.empty_desc': 'ستظهر سجلات النشاط هنا',
        'dashboard.nav.notifications': 'الإشعارات',
        'dashboard.nav.approval_required': 'مطلوب الموافقة على الحساب',
        'settings.desc_placeholder': 'أخبرنا عن نشاطك في مجال القاعات...',
        'settings.billing.subscription_expired': 'انتهى اشتراكك',
        'settings.billing.subscription_expired_desc': 'جدد باقتك لإعادة تفعيل قاعتك.',
        'settings.billing.subscription_expiring': 'ينتهي اشتراكك خلال {days} يوم',
        'settings.billing.limited_offer': 'عرض محدود',
        'settings.billing.venue_count': 'قاعة',
    }
};


export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    // Use next-intl's useLocale() as the source of truth — it reads the locale
    // from the server-side URL params passed through NextIntlClientProvider,
    // so it works correctly during both SSR and client hydration.
    const intlLocale = useLocale() as Language;
    const [language, setLanguageState] = useState<Language>(intlLocale);

    // Sync language state when the intl locale changes (e.g. after navigation)
    useEffect(() => {
        if (intlLocale !== language) {
            setLanguageState(intlLocale);
        }
    }, [intlLocale]);

    useEffect(() => {
        document.documentElement.lang = language;
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        localStorage.setItem('language', language);
    }, [language]);

    // Handle language change
    const handleSetLanguage = useCallback((lang: Language) => {
        // Preserve query params and anchors while swapping locales.
        const fullPath = `${window.location.pathname}${window.location.search}${window.location.hash}`;

        // Use the utility function to properly create localized path
        // This ensures we don't get double locale prefixes
        const newPath = createLocalizedPath(fullPath, lang);

        // Optimistically update state
        setLanguageState(lang);
        document.documentElement.lang = lang;
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
        localStorage.setItem('language', lang);

        // IMPORTANT: Use window.location.href for hard navigation
        // next-intl's router automatically adds locale prefix which causes double locales like /ar/fr/dashboard
        // Hard navigation ensures clean state and proper locale handling
        window.location.href = newPath;
    }, []);

    const t = useCallback((key: string) => {
        const localeTranslations = translations[language] as Record<string, string>;
        return localeTranslations[key] || key;
    }, [language]);

    return (
        <LanguageContext.Provider value={{
            language,
            setLanguage: handleSetLanguage,
            dir: language === 'ar' ? 'rtl' : 'ltr',
            t
        }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
    return context;
};
